### ISSUE TITLE
Configuratie van logging provider(s)

### ISSUE THREAD

**Issue by FilipBruinsHAN** [open-education-api/ooapi-dotnet#39]
Er is geen logging provider geconfigureerd. Zie MSFT doc: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0

Vanuit de HAN willen wij Application Insights gebruiken. Waar hebben andere organisaties de voorkeur voor? We kunnen eventueel log providers configureren o.b.v. configuratie settings, zodat elke organisatie zijn eigen log provider kan kiezen.

**Comment by bartvriesema** [comment]
Binnen de Universiteit Maastricht hebben wij onze eigen logging oplossing, die we gebruiken. Ik zal even met mijn collega's bespreken wat onze wensen hierin zijn, dan kom ik daar morgen op terug.

**Comment by bartvriesema** [comment]
Dit heb ik vandaag even binnen het team besproken. Wij zijn niet bekend met Application Insights en kennen de mogelijkheden van deze applicatie niet, maar wellicht zouden jullie daar wat van kunnen laten zien. De UM is langzaam bezig met het in gebruik nemen van Azure, maar ik moet nog navragen of Application Insights inbegrepen is in onze licentie.

Onze eigen logging kent de mogelijkheid om de logging in een hierarchische structuur weer te geven, vooral voor de systeembeheerders handig. De hoogst mogelijke foutcode bubbelt automatisch naar boven in de structuur, een voorbeeld in het plaatje. 

Wij denken dat we dit middels een generieke interface wel kunnen bewerkstelligen, mits daar de mogelijkheid in zit om een errorlevel mee te geven, een bericht en eventueel een object. Dat object kunnen we als JSON opslaan bij de logging en kan bijvoorbeeld additionele data bevatten.

Wellicht is het handig om even een keer een Teams-meeting te plannen om even de koppen bij elkaar te steken.

Naast de logging is er nog het onderwerp authenticatie, dat wellicht ook middels een interface toegevoegd kan worden. In onze implementatie gebruiken we een filter op de BaseController voor het controlleren van een header apikey. Ik weet niet hoe de HAN dat heeft opgezet. 

Misschien is het sowieso handig even samen te kijken naar welke aanpassingen wij al gedaan hebben, om te voldoen aan de OOAPI-specificatie en de vereisten voor de RIO implementatie. Naast de pull request die ik al had ingediend, heb ik nog wel een aantal aanpassingen gedaan in de logica om alle juiste velden terug te geven, die in de oorspronkelijke implementatie door InHolland nog niet gedaan waren.

**Comment by FilipBruinsHAN** [comment]
Hi Bart, wij kunnen wel wat van application insights laten zien. Lijkt me goed om de andere onderwerpen die je aanstipt ook te bespreken tijdens een Teams-meeting volgende week, ook met InHolland erbij. Kan jij de e-mailadressen van deelnemers van jullie kant naar mij mailen? Mijn e-mailadres volgt het standaard voornaam.achternaam formaat.

**Comment by FilipBruinsHAN** [comment]
Wij hebben application insights toegevoegd met PR #48. Alleen indien de application insights connection string aanwezig is wordt application insights toegevoegd. Indien men andere logging providers wil gebruiken, dan kunnen die op een vergelijkbare configurabele manier worden toegevoegd.
