### ISSUE TITLE
consumer - info wordt niet getoond bij /education-specifications/[UUID]/education-specifications?consumer=XXX

### ISSUE THREAD

**Issue by arthurvanalten** [open-education-api/ooapi-dotnet#63]
bij het opvragen education-specifications van een education-specification wordt de consumer-info niet mee opgehaald.

in GetAllOrderdByAsync() van EducationSpecificationsRepository staat:
        if (!string.IsNullOrEmpty(dataRequestParameters.Consumer))
        {
            set = set.Include(x => x.Consumers.Where(y => y.ConsumerKey.Equals(dataRequestParameters.Consumer)));
        }

dit ontbreekt in GetEducationSpecificationsByEducationSpecificationIdAsync() en in GetEducationSpecificationsByOrganizationIdAsync()

**Comment by bartvriesema** [comment]
Ik heb daarvoor een aparte methode die ik in al die gevallen gebruik gemaakt. Daarbij pas ik de IQueryable aan die aanlsuitend naar de GetAllOrderByAsync gaat.

`    private static IQueryable<EducationSpecification> IncludeConsumerIfNeeded(DataRequestParameters dataRequestParameters, IQueryable<EducationSpecification> set)
    {
        bool includeConsumer = dataRequestParameters != null && !String.IsNullOrEmpty(dataRequestParameters.Consumer);
        if (includeConsumer)
        {
            set = set.Include(x => x.Consumers.Where(y => y.ConsumerKey.Equals(dataRequestParameters.Consumer)));
        }

        return set;
    }`
Formeel zijn we er daarmee nog niet helemaal, want de documentatie schrijft voor dat bij deze expliciete vraag om consumer gegevens, alleen die entiteiten teruggegeven moeten worden waarvoor de gevraagde consumer data ook bestaat.
Zie [documentatie](https://openonderwijsapi.nl/#/technical/consumers-and-profiles/rio) waar het volgende staat:
> All calls returning collections need to support at least the consumer query parameter and should only return entities meant for RIO when this parameter is set to rio, e.g. ?consumer=rio.
