### ISSUE TITLE
class library

### ISSUE THREAD

**Issue by cdunnink** [open-education-api/ooapi-dotnet#64]
Hallo,

Heel mooi dat er nu een implementatie is vanuit het open-education-api-account.
Zodra we met het Deltion College een begin gaan maken met de implementatie zal ik proberen mijn steentje bij te dragen aan dit project.
Wij zijn aan het kijken voor een cannonical-model voor ons integratieplatform binnen Azure (servicebus/apim onder andere).
Zou het ".core"-project van deze solution kunnen dienen als cannonical-model?

groet Coen

**Comment by rvbaast** [comment]
Hoi Coen, 

Nadeel van de class library is dat in dit model er json annotaties evenals datacontract annotaties zitten. Ook zit er nu logica in de 'domain' modellen. Mocht je dit geen bezwaar vinden dan is het technisch te gebruiken als canoniek model. 

Persoonlijk vind ik dat je er teveel code bijkrijgt die je niet 'canoniek' kunt noemen.

Mvg

Rob

**Comment by cdunnink** [comment]
Bedankt voor de info. Dat is inderdaad zo. Ik had nog niet uitvoerig alle classes bekeken. Mooi dat er al over nagedacht is. #60 vraagt nog wel wat ontwerp- en denkwerk. Ik begin nu eerst met een paar basis-classes voor persoon en organisatie. Ik zal #60 in de gaten houden. Ik wil daar ook bij helpen als dat nodig is.
